#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -ex

pack_name=`action-get name`

if [ "$pack_name" = "es-en" ]; then
wget http://cs.jhu.edu/~post/language-packs/language-pack-es-en-phrase-2015-03-06.tgz -O /tmp/lpack.tgz
elif [ "$pack_name" = "ar-en" ]; then
wget http://cs.jhu.edu/~post/language-packs/language-pack-ar-en-phrase-2015-03-18.tgz -O /tmp/lpack.tgz
elif [ "$pack_name" = "zh-en" ]; then
wget http://cs.jhu.edu/~post/language-packs/zh-en-hiero-2016-01-13.tgz -O /tmp/lpack.tgz
fi

rm -rf /opt/language-pack
mkdir /opt/language-pack
tar xvfz /tmp/lpack.tgz -C /opt/language-pack  --strip-components=1
rm -rf /tmp/lpack.tgz
charms.reactive set_state languagepack.installed
hooks/update-status
