#!/usr/bin/perl
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# "Safe" version of paste that dies if the input files have different lengths.

use strict;
use warnings;
use FileHandle;
use List::Util qw/sum reduce/;

binmode STDIN, ':utf8';
binmode STDOUT, ':utf8';

my @fh = map { new FileHandle($_, "< :encoding(UTF-8)") } @ARGV;

for (;;) {
  my @lines = map { $_->getline } @fh;
  
  my $num_done = grep { ! defined $_ } @lines;
  if ($num_done > 0 and $num_done < @lines) {
    print STDERR "* FATAL! unequal file lengths.\n";
    exit 1;
  }
  last if $num_done == @lines;

  chomp(@lines);
  print join("\t", @lines) . $/;
}
